

service: big-mouth # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
